config/routes.rb
Rails.application.routes.draw do
  
  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  devise_for :users
   root 'homes#show'
  
  resources :users, only: [:show, :edit, :update] do
     member do
     	get :following, :followers
     end
   end
    resources :relationships, only: [:create, :destroy]
  get 'relationships' => 'relationships#create'
  delete 'relationships' => 'relationships#destroy'
  resources :posts
  get 'posts/new'
  post 'posts' => 'posts#create'

  get 'tags/:tag', to: 'posts#index', as: "tag"

  resources :posts do
  resources :comments
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
  validates :name, presence: true
 
 has_many :passive_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id", 
                                  dependent: :destroy

 has_many :followers, through: :passive_relationships, source: :follower



 has_many :active_relationships, class_name: "Relationship",
                                 foreign_key: "follower_id",
                                 dependent: :destroy

 has_many :followings, through: :active_relationships, source: :followed

 has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy 



  # def follow(other_user)
  # 	active_relationships.create(followed_id: other_user.id)
  # end 

  # def following?(other_user)
  #   followings.include?(other_user.id)
  #   active_relationships.find_by(followed_id: other_user.id)
  # end
  # def unfollow(other_user )
  # 	active_relationships.find_by(followed_id: other_user.id).destroy
  # end                       

def following?(followed)
relationships.find_by_followed_id(followed)
end

def follow!(followed)
relationships.create!(:followed_id => followed.id)
end

def unfollow!(followed)
relationships.find_by_followed_id(followed).destroy
end


  mount_uploader :avatar, AvatarUploader
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!, only: [:edit, :update]
before_action :check_authorization, only: [:edit, :update]
before_action :set_user, only: [:show, :edit, :update]

def show
	@user = User.find(params[:id])
  
end

def edit
end

 def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, alert: "Could not update, Please try again"
    end
  end


def followers
 redirect_to followers_user_path
end 

def following
 redirect_to following_user_path
end 
private 
 def check_authorization
      unless current_user.id == params[:id].to_i
        redirect_to root_url
      end
    end

def set_user
      @user = User.find(params[:id])
end

def user_params
      params.require(:user).permit( :avatar, :description)
    end
end

app/helpers/users_helper.rb
module UsersHelper
	 def avatar_for(user, options = { size: 80 })
    size = options[:size]
    style = options[:style]
    if user.avatar?
      if size <= 80
        image_tag user.avatar.url(:thumb), width: size, height: size, alt: user.name, class: 'avatar-image', style: style
      else
        image_tag user.avatar.url, width: size, height: size, alt: user.name, class: 'avatar-image', style: style
      end
    else
      image_tag 'default-avatar.png', width: size, height: size, alt: 'avatar image', class: 'avatar-image', style: style
    end
  end
end

app/views/users/_follow.html.erb
<%= link_to "Seguir", relationships_path(user_id: @user.id), class: 'button green-border-button pull-left edit-button' %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user)%>
<div id="follow_form">
	<% if current_user.following?(@user)%>
	    <%render 'unfollow' %>
	<% else %>
	    <%render 'follow' %>
	<% end %>      
</div>
<% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
  <div class="stats">

    <a href="<%= following_user_path(@user)%>">
    <strong id="following" class="stats">
    <%= @user.followings.count%>
    </strong> Siguiendo </a> 

    <a href="<%= followers_user_path(@user)%>">
    <strong id="followers" class="stats">
    <%= @user.followers.count%>
    </strong> Seguidor</a> 

  </div>

app/views/users/_unfollow.html.erb
<%= link_to "Dejar Seguir", relationships_path(user_id: @user.id), method: :delete, class: 'button green-border-button pull-left edit-button' %>

app/views/users/edit.html.erb
<div class="centrar">

<h1>Editar Perfil</h1>


<%= form_for(@user, html: {multipart: true })do |f| %>

<%= f.label :name%>
<%= f.text_field :name%>

<%= f.label :description%>
<%= f.text_area :description, class: "description" %>


 <div class="hero-avatar">
            <label class="change-avatar" id="change-avatar" style="background-image: url('<%= @user.avatar.url %>')">
              <%= f.file_field :avatar %>
              <%= icon('camera') %>
            </label>
          </div>

<%= f.submit "Guardar" %>
<%end %>
</div>

app/views/users/followers.html.erb
<h1>followers</h1>

app/views/users/show.html.erb
<div class="banner-container" data-animation="fadeInUp-fadeOutDown-slow">
  <div class="hero-wrapper">
   
      <div class="profile-info">
        <h1 class="hero-title"><%= @user.name %></h1>

           <div class="avatar-imagen2">
        <%= avatar_for @user, size: 100 %>
        </div>  
        
        <p class="hero-description"><%= @user.description %></p>
      </div>

  
        
    

    <div class="stats">
        


        <button class="button">
         <a href="<%= following_user_path(@user)%>">
            <strong id="following" class="stats">
             <%= @user.followings.count%>
           </strong> Siguiendo 
        </a></button> 


  

        <button class="button">
          <a href="<%= followers_user_path(@user)%>">
           <strong id="followers" class="stats">
             <%= @user.followers.count%>
             <% if @user.followers.count < 10 %>
                </strong> Seguidor 
               <% else %>
                 Seguidores
             <% end %>
         </a>
       </button> 
    <button class="button"> 
         <a href=" <%=%> ">
            <strong id="post" class="stats">
             <%= @user.posts.count%>
           </strong> Relatos 
        </a></button> 



 </div>





  <% if user_signed_in? && !current_user?(@user) %>

         <% if current_user.following?(@user) %>
            <%= link_to "Dejar Seguir", relationship_path(user_id: @user.id), method: :delete, class: 'button green-border-button pull-left edit-button' %>

            <% else %>

             <%= link_to "Seguir", relationships_path(user_id: @user.id), class: 'button green-border-button pull-left edit-button' %>

        <% end %>
           
           

        <% end %> </div>
        <br><br>   

        <% if user_signed_in? && current_user?(@user) %>
        <%= link_to "Edit", edit_user_path(@user), class: 'button green-border-button pull-left edit-button' %>
        <% end %>
 
</div>