config/routes.rb
Rails.application.routes.draw do
  
  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  devise_for :users
   root 'homes#show'
  
  resources :users, only: [:show, :edit, :update] do
     member do
     	get :following, :followers
     end
   end
    resources :relationships, only: [:create, :destroy]
  get 'relationships' => 'relationships#create'
  delete 'relationships' => 'relationships#destroy'
  resources :posts
  get 'posts/new'
  post 'posts' => 'posts#create'

  get 'tags/:tag', to: 'posts#index', as: "tag"

  resources :posts do
  resources :comments
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
	#pertenece a
	belongs_to :user
	 #tiene mucho de
	 has_many :comments, -> { order(created_at: :desc) }, dependent: :destroy
	 validates :title, presence: true,
	 length: { minimum: 5 }

	 default_scope { order('created_at DESC') }
	 belongs_to :category
	 mount_uploader :imagen, ImagenUploader

	 has_many :taggings, dependent: :destroy
	 has_many :tags, through: :taggings

	 has_many :has_categories
	 has_many :categories, through: :has_categories
     delegate :name, to: :user




	 def categories=(value) 
	 	@categories = value

	 end

	 def self.tagged_with(name)
	 	Tag.find_by!(name: name).posts

	 end
	 

	 def all_tags=(names)
	 	self.tags = names.split(",").map do |name|
	 		Tag.where(name: name).first_or_create!

	 	end

	 end


	 def all_tags
	 	tags.map(&:name).join(", ")
	 end



	 # private
	 #    def save_categories
	 #    @categories.each do |category_id|
 	#  	  HasCategory.create(category_id: category_id, post_id: self.id)
	 #         end
	 #    end 	

	end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 # before_action :set_post, only: [:show, :edit, :update, :destroy]
 before_action :authenticate_user!, except: [:index, :show]

def new
	@post = current_user.posts.build
  @categories = Category.all.map { |c| [c.name, c.id]  }
end

def create

  @post = current_user.posts.build(post_params)
  @post.category_id = params[:category_id]
  
  # @post.categories = post_params[:categories]
    if @post.save
	    redirect_to @post
	  else
	    render 'new'
	  end
  end

def show
  @post = Post.find(params[:id])
    @comments = Comment.where(post_id:@post).order("created_at DESC")
end

def index
  if params[:tag]
    @posts = Post.tagged_with(params[:tag])
  else  
    @posts = Post.all
    @posts = Post.order('created_at DESC').paginate(page: params[:page],per_page:5)
  end
    #@posts = Post.order(name: :asc).paginate(page: params[:page],per_page:10)
 
end

def edit
  @post = Post.find(params[:id])
  @categories = Category.all.map { |c| [c.name, c.id]  }
end

def update
  @post = Post.find(params[:id])
 
  if @post.update(post_params)
    redirect_to @post
  else
    render 'edit'
  end
end
 

 def destroy
  
  @post = Post.find(params[:id])
  @post.destroy
 
  redirect_to root_path
end

private
  def post_params
    params.require(:post).permit(:title, :text, :imagen, :all_tags, :category_ids)
  end

def category_params
    params.permit(:category_id)

end

end

app/helpers/posts_helper.rb
module PostsHelper
	def imagen_for(post, options = { size: 1000 })
    size = options[:size]
    style = options[:style]
    if post.imagen?
      if size <= 1000
        image_tag post.imagen.url(:thumb), width: size, height: 401, alt: post.title, class: 'imagen-image', style: style
      else
        image_tag post.imagen.url, width: size, height: 401, alt: post.title, class: 'imagen-image', style: style
      end
    else
      image_tag 'default-avatar.png', width: size, height: 401, alt: 'avatar image', class: 'imagen-image', style: style
    end
  end

def tag_links(tags)
  tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ") 
end

def tag_cloud(tags, classes)
  max = tags.sort_by(&:count).last
  tags.each do |tag|
    index = tag.count.to_f / max.count * (classes.size-1)
    yield(tag, classes[index.round])
  end
end

end

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :class => "form-horizontal post" } do |f| %>

  <% if @post.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.label :title, 'Titulo' %>
    <div class="titulo">
    
  <%= f.text_field :title,  :size=>'50', :height=>'254', :class => 'form-control form-control-lg', :placeholder => 'Titulo del blog' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
<br>
  <div class="contenido form-inputs">
    <%= f.label :text, 'Contenido'%>
   <%= f.hidden_field :text, id: :post_body, class: "form-control" %>
   
    <trix-editor  input="post_body"></trix-editor>
    <%=f.error_span(:text) %>
  </div>
 <br>

<br>
  <div>
    <h3>Categorias</h3>
  
     <div class="field">
   
     <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Sleccione Uno!")%>
     </div>

  
  </div>


 <br>
<div class="hero-avatar">
            <label class="change-avatar" id="change-avatar" style="background-image: url('<%= @post.imagen.url %>')">
              <%= f.file_field :imagen %>
              <%= icon('camera') %>
            </label>
            
          </div>



  <div class="form-actions">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                posts_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/posts/_index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <a><h1 class="text-indigo">Relatos Recientes</h1>
</a></div>

  
 <table>
<ul>

        <tr>
        <th><%= model_class.human_attribute_name(:titulo) %>  </th>
          <th><%= model_class.human_attribute_name(:publicado)%>  </th>
          
              
          <% if user_signed_in? %>  

          <th><%=t '.actions', :default => t("helpers.actions") %></th>
          <th><%= model_class.human_attribute_name(:Categorias)%>  </th>
            <% end %>
        </tr><br>

 
  <tbody style="text-transform: capitalize;">
    <% @posts.each do |post| %>
      <tr>
        
        <td class="post_panel2"><%= link_to post.title, post %></td>
        <td class="post_panel2">publicado el <%= post.created_at %></td>
     
        <td>
        
         <% if user_signed_in? && current_user?(post.user) %>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      post_path(post), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_post_path(post), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      post_path(post),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
                          <% end %>
        </td>
      </tr><br>
    <% end %>


  </tbody>

 </table> 
</ul>



<div class="centrar">
<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>  

 <% if user_signed_in? %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-lg btn-primary' %>
  <% end %>
            <br>
 </div>

app/views/posts/_post.html.erb
    <!-- AQUIIII EL LANDING PAGE
  -->

 <div  class="pin post_panel level-2", style="text-transform: capitalize;" >
   <div class="colorr">
   <%= link_to avatar_for(post.user, size:38), post.user %> 
    <a><%= link_to post.user.name, post.user %></a>
     
   </div>

   <br>
           <div class="post_panel_imagen level-3 img-fluid" style="height: 150px;">
            <br>
            <%= imagen_for(post, size:1200) %>
          </div>
  <br>
            <div class="main-body level-4">
              <center>
                  <h3 class="post-title">
                     <%= link_to post.title, post %>   
                  </h3>
              </center> 
            </div>
   
           <div class="icono">
             <span class="text-nuted pull-right">
              <i class="far fa-heart" style="color:#BE81F7;"></i>
              <i class="far fa-comments" style="color:#BE81F7;"></i>
              <%= post.comments.count %>
              <i class="far fa-eye" style="color:#BE81F7;"></i>
            </span>
          </div>

          
     

  </div>      

app/views/posts/_post_metadata.html.erb
<div class="post-metadata">
  <%= avatar_for post.user, size: 40 %>
  <div class="post-info">
    <%= react_component("PopoverLink", { user_id: post.user.id, url: user_path(post.user), children: post.username }) %>
    <small><%= time_ago_in_words(post.created_at) %> ago &#149; <%= post_length_in_minutes(post.body) %></small>
  </div>
</div>

app/views/posts/_social_share.html.erb
<div class="social-share-wrapper">
  <div class="social-share">
    <a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= post_url(post) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0)"
       class="ico fb">
       <i class="fa fa-facebook"></i>
    </a>
    <a onclick="javascript:window.open('http://twitter.com/share?text=<%= post.title %> by <%= post.user.name %> - &amp;url=<%= post_url(post) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0)"
       class="ico tw">
       <i class="fa fa-twitter"></i>
    </a>
    <a onclick="javascript:window.open('http://plus.google.com/share?url=<%= post_url(post) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0)"
       class="ico gp">
       <i class="fa fa-google-plus"></i>
    </a>
    <span class="text"><em>SHARE</em></span>
    <span class="ico-share"><i class="fa fa-share-alt"></i></span>
  </div>
</div>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1>Post Publicados</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
     
      <th><%= model_class.human_attribute_name(:titulo) %></th>
      <th><%= model_class.human_attribute_name(:publicado) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        
        <td class="post_panel"><%= link_to post.title, post %></td>
        <td class="post_panel">publicado el <%= post.created_at %></td>
        <td>
          <% if user_signed_in? %>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      post_path(post), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_post_path(post), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      post_path(post),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
                          <% end %>
        </td>
      </tr>
    <% end %>


  </tbody>
</table>
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>  
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-lg btn-block btn-primary' %>

            <br>
 

app/views/posts/index.js.erb
$('#posts').append('<%= j render("post_page_header") %>');
$('#posts').append('<%= j render(@posts) %>');
<% if @posts.netx_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@posts) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
    <h1 class="uk-h2 uk-margin-top-remove">Nuevo Relato</h1>
</div>
<div class="container-new">
<%= render :partial => 'form' %>
</div>

app/views/posts/show.html.erb
  <!--   <div class="pull-right">
      <%= render partial: 'posts/social_share', locals: { post: @post } %>
    </div> -->
    <div style="text-transform: capitalize;"> 
     <h1 class="hero-title"><%= @post.title %></h1>
     <dl class="dl-horizontal">

      <div class="hero-wrapper">
        <header class="hero">

          <div class="hero-avatar">
            <%= imagen_for @post, size: 1200 %>
          </div>
        </header>
      </div>
    </div>  
    



    <%- model_class = Post -%>


    <div class="post-show"">
      <td>publicado el <%=  @post.created_at.strftime("%Y-%m-%d") %></td>
      <br>

      <div class="perfil-avatar">
       <%= avatar_for(@post.user, size:40) %>   
       <%= link_to @post.user.name, @post.user %>
       <br>
       <div class="heart" style="float: right;">
        <i class="far fa-heart " style="color:#BE81F7;"></i>
        <i class="far fa-comment" style="color:#BE81F7;">  </i>
        <%= @post.comments.count %>
        
        <i class="far fa-eye" style="color:#BE81F7;"></i>
      </div> 

    </div><hr class="uk-grid-divider">
    <p><%=raw @post.text %></p>
  </div>
  
</dl>

<br>
<br>


<small >


</small>


<div class="centrar">
  <h3><%= @post.comments.count %> Comentarios</h3>
</div>


<%= render @post.comments %>




  <h3 class="uk-h2 uk-margin">Comentarios</h3>




<%= render "comments/form"%>

      <% if user_signed_in? && current_user?(@post.user) %>

      <div class="centrar">
        <%= link_to t('.back', :default => t("helpers.links.back")),
        posts_path, :class => 'btn btn-default'  %>

        <%= link_to t('.edit', :default => t("helpers.links.edit")),
        edit_post_path(@post), :class => 'btn btn-default' %>

        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
        post_path(@post),
        :method => 'delete',
        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
        :class => 'btn btn-danger' %>
      </div>
      <% end %>